//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angelo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Angelo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !WA:2!nB1tZTTXvCtZ0joyAtTzuLJDtArCNOkvRQktBz7yv1wckslztjXcsB52kpKlawqGiqaODxqjLP)jLhY4l5I(iOZ5eV2z64rFcEJMo9dGo3t(tqF7cqjlQANzuUukrU7(23B399737TVn3tlWnNBM7pZ9k0TGtbNx8XhArS30HffxokiI9OC5Yvp)SZm3rwrmhkZiBsJvJcP7lIS7rzC)OWln9)XKBtcO5TsvSnB31CD5uXsVS9lZ9Lx4cxCFgTdQzZDJPMDyrjX7NQzd)VGMFqA)09mp(5qsIWlITwSaTHRzzhf663rJrSvcURjxqycnd)qFHMLl2W906ly(D6GNORpblR7xTVd1kX1vUTSLQuRE1NuZqipdKegPyFEmniyzhU2r8elApAOObQT)odAvUuJMTA0SKztJeCtSIdi7szhRwDgfvZSr9k1QzQKyTeLei8mdjDPCT9scZocAzoAfhCWT0R7Vdn4v(HcklKe80u87RhqcTr)TEeoHv5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WA {
            get {
                return ResourceManager.GetString("WA", resourceCulture);
            }
        }
    }
}
